// <auto-generated />
namespace SimplyCooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class przepis_skladniki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(przepis_skladniki));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021550038_przepis_skladniki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
