// <auto-generated />
namespace SimplyCooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class zmiany_comment_photo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zmiany_comment_photo));
        
        string IMigrationMetadata.Id
        {
            get { return "201805070816322_zmiany_comment_photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
