// <auto-generated />
namespace SimplyCooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class equipmentID_to_recipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(equipmentID_to_recipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201806091332045_equipmentID_to_recipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
